// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATodQHkL3feattIMyYucIweKYxTHsBPvo',
    appId: '1:981749426378:web:b51eda752c808b27632c33',
    messagingSenderId: '981749426378',
    projectId: 'mynotes-8e2e8',
    authDomain: 'mynotes-8e2e8.firebaseapp.com',
    storageBucket: 'mynotes-8e2e8.firebasestorage.app',
    measurementId: 'G-7QT22ECMC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPLG0R7NoZfu4zWgc9mZ8rfGBu3TpEJmk',
    appId: '1:981749426378:android:d279b6d837072b16632c33',
    messagingSenderId: '981749426378',
    projectId: 'mynotes-8e2e8',
    storageBucket: 'mynotes-8e2e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8h16yl54xLqDudK2NQDdHBsut_kByNz8',
    appId: '1:981749426378:ios:2b87ea2a79d972f1632c33',
    messagingSenderId: '981749426378',
    projectId: 'mynotes-8e2e8',
    storageBucket: 'mynotes-8e2e8.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8h16yl54xLqDudK2NQDdHBsut_kByNz8',
    appId: '1:981749426378:ios:2b87ea2a79d972f1632c33',
    messagingSenderId: '981749426378',
    projectId: 'mynotes-8e2e8',
    storageBucket: 'mynotes-8e2e8.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATodQHkL3feattIMyYucIweKYxTHsBPvo',
    appId: '1:981749426378:web:e6e5d1d09792c4cd632c33',
    messagingSenderId: '981749426378',
    projectId: 'mynotes-8e2e8',
    authDomain: 'mynotes-8e2e8.firebaseapp.com',
    storageBucket: 'mynotes-8e2e8.firebasestorage.app',
    measurementId: 'G-R5K3KTPLDW',
  );
}
